# www.hireq.ai uwsgi .ini file
[uwsgi]

# Django-related settings
# the base directory (full path)
chdir           = /var/www/www.hireq.ai
# Django's wsgi file
wsgi-file          = /var/www/www.hireq.ai/hq/wsgi.py
# the virtualenv (full path)
home            = /var/www/www.hireq.ai/env

# process-related settings
# master
master          = true
# maximum number of worker processes
processes       = 2

enable-threads = true

threads = 4
# the socket (use the full path to be safe
socket          = /var/www/www.hireq.ai/hq.sock
# ... with appropriate permissions - may be needed
chmod-socket    = 666
# clear environment on exit
vacuum          = true
uid = www
gid = www
# log
logto = /var/log/uwsgi/www.hireq.ai.log