# the upstream component nginx needs to connect to
upstream hq {
    server unix://var/www/www.hireq.ai/hq.sock; # for a file socket
}

# Redirect http to https
server {
    listen          80;
    server_name     hireq.ai www.hireq.ai;
    rewrite ^/(.*)  https://www.hireq.ai/$1 permanent;
}

# non-www to www
#server {
#    listen 443 ssl;
#    server_name hireq.ai;
#    ssl_certificate /etc/letsencrypt/live/hireq.ai/fullchain.pem;
#    ssl_certificate_key /etc/letsencrypt/live/hireq.ai/privkey.pem;
#    return 301 https://www.hireq.ai$request_uri;
#}
# configuration of the server
server {
    # the port your site will be served on
    listen      443 ssl http2;
    listen      [::]:443 ssl http2;

    # the domain name or IP to serve for
    server_name www.hireq.ai;

    if ($host = 'hireq.ai') {
      return 301 https://www.hireq.ai$request_uri;
    }

    charset utf-8;
    # max upload size; adjust to taste
    client_max_body_size 25M;

    ssl_certificate         /etc/letsencrypt/live/www.hireq.ai/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/www.hireq.ai/privkey.pem;

    # Django media file
    location /media {
        alias /var/www/www.hireq.ai/media;
    }
    # Django static file
    location /static {
        alias /var/www/www.hireq.ai/static;
    }
     #For favicon
    location  /favicon.ico {
       alias /var/www/www.hireq.ai/static/favicon.ico;
    }

     #For well-known
    location  /.well-known {
       alias /var/www/www.hireq.ai/.well-known;
    }

    # Finally, send all non-static/media requests to Django.
    location / {
        uwsgi_pass hq;
        include /etc/nginx/uwsgi_params;
    }
}