# Generated by Django 5.1.3 on 2024-12-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='education',
            name='college',
        ),
        migrations.RemoveField(
            model_name='educationdeleted',
            name='college',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employmentdeleted',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='education',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='educationdeleted',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='employmentdeleted',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='template',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='candidate',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='EducationDeleted',
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
        migrations.DeleteModel(
            name='EmploymentDeleted',
        ),
        migrations.DeleteModel(
            name='PDFTemplate',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
