# Generated by Django 5.1.3 on 2024-12-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_hquser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='current_location',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notice_period',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='willing_to_locate',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, max_length=32),
        ),
    ]
