# Generated by Django 5.1.3 on 2024-12-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobapplication_current_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='category',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='experience',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='job_type',
            field=models.CharField(default='Full Time', max_length=128),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='qualifications',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='responsibilities',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='skills_required',
            field=models.TextField(),
        ),
    ]
