# Generated by Django 5.1.3 on 2024-12-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_jobdescription_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='current_company',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='education',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APP', 'Applied'), ('1ST_SCH', '1st round scheduled'), ('1ST_COM', '1st round completed'), ('CLI_SCH', 'Client interview scheduled'), ('CLI_COM', 'Client interview completed'), ('1ST_REJ', 'First round reject'), ('CLI_REJ', 'Client round reject'), ('TBS', 'To be scheduled'), ('NR', 'Not reachable'), ('REJ', 'Rejected'), ('NO_SHOW', 'No show')], max_length=32),
        ),
    ]
