# Generated by Django 5.1.3 on 2024-12-24 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_jobapplication_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., LinkedIn, Indeed, Company Website', max_length=255, unique=True)),
                ('code', models.CharField(help_text='A short, unique code for the URL parameter. e.g., linkedin, indeed, website', max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='referral_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.referralsource'),
        ),
    ]
