# Generated by Django 5.1.3 on 2024-12-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_referralsource_alter_jobapplication_referral_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralsource',
            name='id',
        ),
        migrations.AlterField(
            model_name='referralsource',
            name='code',
            field=models.CharField(help_text='A short, unique code for the URL parameter. e.g., linkedin, indeed, website', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
