# Generated by Django 5.1.3 on 2025-01-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_referralsource_id_alter_referralsource_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='willing_to_locate',
            field=models.CharField(choices=[('no', 'No'), ('undecided', 'Undecided'), ('yes', 'Yes')], default='undecided', max_length=32),
        ),
    ]
