# Generated by Django 5.1.3 on 2025-01-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_jobapplication_willing_to_locate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='current_salary',
            new_name='current_ctc',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='expected_salary',
            new_name='expected_ctc',
        ),
    ]
