# Generated by Django 5.1.3 on 2025-01-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_current_salary_jobapplication_current_ctc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Current CTC'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='expected_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expected CTC'),
        ),
    ]
