# Generated by Django 5.1.3 on 2025-01-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_jobapplication_current_ctc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='comments_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Current CTC(LPA)'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='current_location',
            field=models.CharField(max_length=256, null=True, verbose_name='Current location(City)'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='expected_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expected CTC(LPA)'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='Years Of Experience'),
        ),
    ]
