# Generated by Django 5.1.3 on 2025-01-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_jobapplication_comments_editable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='comments_editable',
        ),
    ]
