"""
Django settings for hq project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from decouple import config, Csv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'widget_tweaks',
    'django_summernote',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',
    'corsheaders',
    'django_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8080",
]

ROOT_URLCONF = 'hq.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hq.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# Email Settings
EMAIL_BACKEND = 'smtp2go_django.email_backend.Smtp2goEmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='mail.smtp2go.com')
EMAIL_PORT = config('EMAIL_PORT', default=2525, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
os.environ['SMTP2GO_API_KEY'] = config('SMTP2GO_API_KEY')


# Send error reports to ADMINS
ADMINS = [('HireSure', 'suport@hiresure.ai'),]
SERVER_EMAIL = 'support@hireq.ai'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'

# Static files (CSS, JavaScript, Images)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

DATE_INPUT_FORMATS = ['%d-%b-%Y','%Y-%m-%d','%b %d %Y','%b-%d-%Y','%d-%M-%Y','%j-%M-%Y']

CLOUDINARY = {
  'cloud_name': config('CLOUDINARY_CLOUD_NAME'),
  'api_key': config('CLOUDINARY_API_KEY'),
  'api_secret': config('CLOUDINARY_API_SECRET'),
}

# Environment. Possible values are dev/stage/prod
env = config('APP_ENV', default='demo')
if env == 'prod':
    QLDB_LEDGER = 'hiresure'
    DEFAULT_FROM_EMAIL = config('PROD_DEFAULT_FROM_EMAIL', default='HireQ.ai <support@hireq.ai>')
    CS_MANAGER_EMAILS = ['spport@hiresure.ai']
    HQ_OWNER_EMAILS = ['support@hiresure.ai']
    DEBUG = False
    BASE_URL = config('PROD_BASE_URL', default='https://www.hireq.ai/')
    DATABASES = {
        'default': {
            'ENGINE': config('DB_ENGINE', default='django.db.backends.mysql'),
            'NAME': config('PROD_DB_NAME'),
            'USER': config('PROD_DB_USER'),
            'PASSWORD': config('PROD_DB_PASSWORD'),
            'HOST': config('PROD_DB_HOST'),
            'PORT': config('PROD_DB_PORT', default=''),
        },
    }
else:  # Local development
    QLDB_LEDGER = 'hiresure_local'
    DEFAULT_FROM_EMAIL = config('DEV_DEFAULT_FROM_EMAIL', default='maan@launchxlabs.com')
    HQ_OWNER_EMAILS = ['maan@launchxlabs.com']
    DEBUG = config('DEBUG', default=True, cast=bool)
    BASE_URL = config('DEV_BASE_URL', default='http://127.0.0.1:8000/')
    DATABASES = {
        'default': {
            'ENGINE': config('DB_ENGINE', default='django.db.backends.mysql'),
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='3306'),
        },
    }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Override if there is local_settings
#try:
#    from .local_settings import *
#except ImportError as e:
#    pass