# Generated by Django 2.1 on 2019-02-16 05:44

import assessment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('display_name', models.CharField(default='noName.com', max_length=16)),
                ('display_header', models.CharField(default='noName.com OTP Psychometric Test', max_length=128)),
                ('api_key', models.CharField(default=assessment.models.token_alphanum8, max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='unique id for the concept', max_length=128, unique=True)),
                ('display_name', models.CharField(help_text='display name for the concept', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, help_text='comma seperated tags for the question', max_length=1024, null=True)),
                ('type', models.CharField(default='mcq', help_text='type of question like MCQ etc', max_length=32)),
                ('html', models.TextField(help_text='question html')),
                ('is_active', models.BooleanField(default=False, help_text='make active only after quality check')),
                ('sme_note', models.TextField(blank=True, help_text='SME can write a note for other reviewers', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.Concept')),
            ],
            options={
                'db_table': 'assessment_question_bank',
            },
        ),
        migrations.CreateModel(
            name='QuestionBankOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(help_text='option html')),
                ('is_correct', models.BooleanField(default=False, help_text='True if the option is correct')),
                ('sequence', models.PositiveSmallIntegerField(help_text='order in which the options will be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.QuestionBank')),
            ],
            options={
                'db_table': 'assessment_question_bank_option',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='unique id for the quiz', max_length=128, unique=True)),
                ('display_name', models.CharField(help_text='display text for quiz', max_length=256)),
                ('is_timed', models.BooleanField(default=False)),
                ('time_min', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuizConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_questions', models.IntegerField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.Concept')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.Quiz')),
            ],
            options={
                'db_table': 'assessment_quiz_concept',
            },
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(help_text='sequence in which questions will be displayed')),
                ('selected_index', models.PositiveSmallIntegerField(help_text='index which is selected', null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False, help_text='user can flag a question for review during quiz')),
                ('submitted_at', models.DateTimeField(help_text='time at which the question is submitted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.QuestionBank')),
            ],
            options={
                'db_table': 'assessment_quiz_response',
            },
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pub', models.CharField(default=assessment.models.token_alphanum16, help_text='public id', max_length=32, unique=True)),
                ('key', models.CharField(default=assessment.models.token_alphanum16, help_text='secret key', max_length=32, unique=True)),
                ('num_questions', models.PositiveSmallIntegerField(help_text='total number of questions', null=True)),
                ('num_correct', models.PositiveSmallIntegerField(default=0, help_text='number of correct answers. will be calculated after submit')),
                ('update_url', models.CharField(blank=True, help_text='url where quiz result will be POSTed', max_length=1024, null=True)),
                ('forward_url', models.CharField(help_text='forward to this url after test is submitted', max_length=1024)),
                ('var', models.CharField(help_text='optional variable to be passed back to the client', max_length=64, null=True)),
                ('started_at', models.DateTimeField(help_text='time at which the quiz started', null=True)),
                ('expires_at', models.DateTimeField(help_text='time at which the quiz expires', null=True)),
                ('submitted_at', models.DateTimeField(help_text='time at which quiz is submitted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.Client')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.Quiz')),
            ],
            options={
                'db_table': 'assessment_user_quiz',
            },
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='user_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.UserQuiz'),
        ),
    ]
